### ISSUE TITLE
Moteur de recherche avec Pagefind

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#150]
- [x] Maquette 
- [x] Interface utilisateur
- [x] A11y
- [x] Automatisation du flux (génération de l'index de recherche pendant le build)
- [x] Build du package.json dans le thème
- [x] Config de pagefind (pagefind.yaml) qui doit être dans le thème 
- [x] Finalisation de la config (exclusion)
- [ ] Chargement de la lib js en module
- [ ] Idée d'Alex : pourquoi ne pas charger le JS quand les gens font une recherche ? Quid du CSS ?
- [x] CORS : réparer le script inline et le chargement des fragments
- [x] Faire une config clean

```yml
search:
  active: true
  interface:
    position: menu // menu | fixed
```
