### ISSUE TITLE
Block pages 

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme-aaa#44]
Modifier le format de donnée en passant directement les urls des pages

> Après migration de tous les sites en AAA : à faire en synchro avec Osuny pour ne pas casser les sites

```
pages:
        - page: /blocks/tous-les-blocks/
          slug: /blocks/tous-les-blocks/
        - page: /blocks/tous-les-blocks-pleine-largeur/
          slug: /blocks/tous-les-blocks-pleine-largeur/
        - page: /blocks/blocks-de-base/
          slug: /blocks/blocks-de-base/
```

```
pages:
        - /blocks/tous-les-blocks/
        - /blocks/tous-les-blocks-pleine-largeur/
        - /blocks/blocks-de-base/
```

**Comment by alexisben** [comment]
Actuellement on a ça : 
```
data:
      page: /blocks/
      show_main_description: true
      show_descriptions: true
      show_images: true
      layout: grid
      pages:
        - page: /blocks/tous-les-blocks/
          slug: /blocks/tous-les-blocks/
        - page: /blocks/tous-les-blocks-pleine-largeur/
          slug: /blocks/tous-les-blocks-pleine-largeur/
        - page: /blocks/blocks-de-base/
          slug: /blocks/blocks-de-base/
```

Il faut faire un tour voir s'il y a encore du legacy avec .slug (au lieu de .page)
