### ISSUE TITLE
Précédent suivant dans les pages

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#74]
Page précédente / page suivante, en fonction de l'ordre dans l'arborescence

Peut-être activé par défaut et désactivable ?

```
params:
  pages:
    navigation:
      active: true
      format: links # links | grid | list
```
