### ISSUE TITLE
Le plan du site n'est pas correct

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#76]
https://www.iut.u-bordeaux-montaigne.fr/plan-du-site/

**Comment by arnaudlevy** [comment]
La TOC ne fonctionne pas

**Comment by arnaudlevy** [comment]
https://example.osuny.org/plan-du-site/

là elle fonctionne mais le scrollspy ne voit pas les titres du bas (après les blocs)

**Comment by alexisben** [comment]
Le thème doit pas être à jour sur bdx montaigne si ?

**Comment by alexisben** [comment]
Dans les data, le toc devrait être autorisé : 

Actuellement on a : 
```
full_width: false
design:
  full_width: false
  toc:
    present: false
    offcanvas: false
```
<img width="381" alt="image" src="https://user-images.githubusercontent.com/4630530/213653588-bf8d4173-d7de-49c6-b1ac-dae44ad9ec29.png">
